# fly.toml app configuration file generated for vb-email-consumer on 2025-11-04T13:13:03+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vb-email-consumer'
primary_region = 'arn'

[build]

[[vm]]
  size = 'shared-cpu-1x'
